In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [7]:
initial_Rf = 1.1
initial_A = 45
initial_B = 45

initial_price = np.array([1 / initial_Rf, initial_A, initial_B])

In [8]:
final_Rf = np.array([1] * 3) # 3states

final_A = np.array([75, 55, 20])

final_B = np.array([60, 50, 40])

final = np.concatenate((final_Rf, final_A, final_B))
final

array([ 1,  1,  1, 75, 55, 20, 60, 50, 40])

In [9]:
vector = final.reshape((3,3)).transpose()
vector

array([[ 1, 75, 60],
       [ 1, 55, 50],
       [ 1, 20, 40]])

In [10]:
state_price = \
    np \
        .matmul(
            initial_price, 
            np.linalg.inv(vector)
        )

In [12]:
vector_of_risk_neutral_probability = \
    state_price * initial_Rf

vector_of_risk_neutral_probability

array([0.25, 0.45, 0.3 ])

In [17]:
payoff_vector = \
    np \
        .where(
            final_A + final_B - 100 > 0, 
            final_A + final_B - 100, 
            0
        )

In [20]:
option_price = round(sum(payoff_vector * state_price), 2)
option_price

10.0

In [9]:
# constructing P and Q
views = np.array([1, 0, 0, 
                  0, 1, -1]) # relative view where weights sum to 0 

returns = np.array([0.05, 
                    0.01]) # second will outperform 3rd by 0.01

P = views.reshape(2, 3)

Q = returns.reshape(2,1)

P
Q

array([[0.05],
       [0.01]])